// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -source=main.go -destination=mock_client.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIndicator is a mock of Indicator interface.
type MockIndicator struct {
	ctrl     *gomock.Controller
	recorder *MockIndicatorMockRecorder
}

// MockIndicatorMockRecorder is the mock recorder for MockIndicator.
type MockIndicatorMockRecorder struct {
	mock *MockIndicator
}

// NewMockIndicator creates a new mock instance.
func NewMockIndicator(ctrl *gomock.Controller) *MockIndicator {
	mock := &MockIndicator{ctrl: ctrl}
	mock.recorder = &MockIndicatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndicator) EXPECT() *MockIndicatorMockRecorder {
	return m.recorder
}

// EMA mocks base method.
func (m *MockIndicator) EMA() []float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EMA")
	ret0, _ := ret[0].([]float64)
	return ret0
}

// EMA indicates an expected call of EMA.
func (mr *MockIndicatorMockRecorder) EMA() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EMA", reflect.TypeOf((*MockIndicator)(nil).EMA))
}

// MACD mocks base method.
func (m *MockIndicator) MACD() ([]float64, []float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MACD")
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].([]float64)
	return ret0, ret1
}

// MACD indicates an expected call of MACD.
func (mr *MockIndicatorMockRecorder) MACD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MACD", reflect.TypeOf((*MockIndicator)(nil).MACD))
}

// RSI mocks base method.
func (m *MockIndicator) RSI(period int) ([]float64, []float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RSI", period)
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].([]float64)
	return ret0, ret1
}

// RSI indicates an expected call of RSI.
func (mr *MockIndicatorMockRecorder) RSI(period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RSI", reflect.TypeOf((*MockIndicator)(nil).RSI), period)
}

// SMA mocks base method.
func (m *MockIndicator) SMA(period int) []float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SMA", period)
	ret0, _ := ret[0].([]float64)
	return ret0
}

// SMA indicates an expected call of SMA.
func (mr *MockIndicatorMockRecorder) SMA(period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SMA", reflect.TypeOf((*MockIndicator)(nil).SMA), period)
}

// StochPrice mocks base method.
func (m *MockIndicator) StochPrice() ([]float64, []float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StochPrice")
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].([]float64)
	return ret0, ret1
}

// StochPrice indicates an expected call of StochPrice.
func (mr *MockIndicatorMockRecorder) StochPrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StochPrice", reflect.TypeOf((*MockIndicator)(nil).StochPrice))
}

// StochRSI mocks base method.
func (m *MockIndicator) StochRSI(rsiPeriod int) ([]float64, []float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StochRSI", rsiPeriod)
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].([]float64)
	return ret0, ret1
}

// StochRSI indicates an expected call of StochRSI.
func (mr *MockIndicatorMockRecorder) StochRSI(rsiPeriod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StochRSI", reflect.TypeOf((*MockIndicator)(nil).StochRSI), rsiPeriod)
}
